### ISSUE TITLE
AppDomain requests unrestricted access upon creation

### ISSUE THREAD

**Issue by Rene-Sackers** [jduv/AppDomainToolkit#25]
Thanks for this great library!

Unfortunately, I have an issue.

I am trying to create a sort of plugin-in based application. Where the plugins have very restricted access. Basically plain C#, and an API that will be exposed.
When I try to restrict the created app domain, it seems to instantly demand unrestricted permissions when the AppDomain gets created:

![error](http://i.imgur.com/lZLOgO6.png)

Do you have any clue why this is happening?
I've uploaded the project to GitHub, you may view it [here](https://github.com/Rene-Sackers/SandboxedAppDomains/blob/master/src/CSharpSandbox.Host/ScriptInstance.cs#L43).

**Comment by jduv** [comment]
This would be some of the semantics of application domains built into the core MSFT libraries. I suppose there'd be a way to pass a permission set in and utilize that, but that wasn't something I needed when I wrote this library. Feel free to update the code and submit a PR. This project needs some more love since I do not have enough time at the moment to maintain it and develop more features.

**Comment by Rene-Sackers** [comment]
Damnit, I totally failed at linking the pull request... Oh well, here you go: https://github.com/jduv/AppDomainToolkit/pull/26

**Comment by Rene-Sackers** [comment]
Cool, thanks for the merge. I'll wait for the NuGet update.
Now to figure out if I can ommit the `new ReflectionPermission(ReflectionPermissionFlag.MemberAccess);` permission.

**Comment by jduv** [comment]
NuGet will come later in the week. Do you need it now? Dealing with day job fires.

**Comment by Rene-Sackers** [comment]
I'm good for now, I'll just build it locally, given you don't mind if I have that DLL published inside my project until the NuGet arrives?

**Comment by jduv** [comment]
That's fine. Or you can ship me the build/package and I can toss it into nuget, your call. I don't have my tooling working on my new machine yet. This is a community library, so I expect you'd ensure there are no breaking changes by running tests etc.

**Comment by Rene-Sackers** [comment]
[Release.zip](https://github.com/jduv/AppDomainToolkit/files/1001781/Release.zip)
![Tests](http://i.imgur.com/TolYM2y.png)
Will that do? All unit tests are passing, plus my own implementation seems to work fine after the change :)

**Comment by jduv** [comment]
Rock on.

**Comment by Rene-Sackers** [comment]
@jduv Hey sorry to poke you on this, but I don't think you ever updated the NuGet :)

**Comment by jduv** [comment]
Yeah I’m totally a slacker on this—sorry.

I can get to it tomorrow. Starting your own company is hard ;).

-jduv

On November 21, 2017 at 3:10:55 PM, René Sackers (notifications@github.com)
wrote:

@jduv <https://github.com/jduv> Hey sorry to poke you on this, but I don't
think you ever updated the NuGet :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jduv/AppDomainToolkit/issues/25#issuecomment-346146576>,
or mute the thread
